from tennis import Player, Match

'''based on post-Wimbledon 2023 rankings (as of Monday 17th July 2023)'''
alcaraz = Player("Carlos Alcaraz", 9675)
djokovic = Player("Novak Djokovic", 8795)
medvedev = Player("Daniil Medvedev", 6520)
ruud = Player("Casper Ruud", 5005)
tsitsipas = Player("Stefanos Tsitsipas", 4850)
rune = Player("Holger Rune", 4825)
rublev = Player("Andrey Rublev", 4525)
sinner = Player("Jannik Sinner", 3975)
fritz = Player("Taylor Fritz", 3310)
tiafoe = Player("Frances Tiafoe", 3130)
khachanov = Player("Karen Khachanov", 3035)
auger_aliassime = Player("Felix Auger-Aliassime", 2770)
norrie = Player("Cameron Norrie", 2610)
paul = Player("Tommy Paul", 2320)
coric = Player("Borna Coric", 2315)
musetti = Player("Lorenzo Musetti", 2290)
hurkacz = Player("Hubert Hurkacz", 2195)
de_minaur = Player("Alex De Minaur", 2150)
zverev = Player("Alexander Zverev", 1720)
f_cerundolo = Player("Francisco Cerundolo", 1655)
dimitrov = Player("Grigor Dimitrov", 1600)
carreno_busta = Player("Pablo Carreno Busta", 1550)
shapovalov = Player("Denis Shapovalov", 1515)
struff = Player("Jan-Lennard Struff", 1500)
bautista_agut = Player("Roberto Bautista Agut", 1480)
jarry = Player("Nicolas Jarry", 1396)
bublik = Player("Alexander Bublik", 1384)
korda = Player("Sebastian Korda", 1365)
evans = Player("Daniel Evans", 1321)
nishioka = Player("Yoshihito Nishioka", 1315)
eubanks = Player("Christopher Eubanks", 1304)
berrettini = Player("Matteo Berrettini", 1262)
lehecka = Player("Jiri Lehecka", 1243)
etcheverry = Player("Tomas Martin Etcheverry", 1231)
davidovich_fokina = Player("Alejandro Davidovich Fokina", 1185)
griekspoor = Player("Tallon Griekspoor", 1184)
kyrgios = Player("Nick Kyrgios", 1175)
mannarino = Player("Adrian Mannarino", 1146)
shelton = Player("Ben Shelton", 1085)
humbert = Player("Ugo Humbert", 1036)
murray = Player("Andy Murray", 1030)
sonego = Player("Lorenzo Sonego", 1025)
safiullin = Player("Roman Safiullin", 1023)
kecmanovic = Player("Miomir Kecmanovic", 1010)
van_de_zandschulp = Player("Botic Van De Zandschulp", 1000)
hanfmann = Player("Yannick Hanfmann", 961)
wolf = Player("J.J. Wolf", 953)
ruusuvuori = Player("Emil Ruusuvuori", 926)
gasquet = Player("Richard Gasquet", 920)
barrere = Player("Gregoire Barrere", 914)
ymer = Player("Mikael Ymer", 901)
karatsev = Player("Aslan Karatsev", 888)
zapata_miralles = Player("Bernabe Zapata Miralles", 871)
fucsovics = Player("Marton Fucsovics", 867)
djere = Player("Laslo Djere", 865)
elahi_galan = Player("Daniel Elahi Galan", 863)
nakashima = Player("Brandon Nakashima", 855)
ofner = Player("Sebastian Ofner", 855)
mcdonald = Player("Mackenzie McDonald", 845)
carballes_baena = Player("Roberto Carballes Baena", 845)
lajovic = Player("Dusan Lajovic", 839)
giron = Player("Marcos Giron", 830)
baez = Player("Sebastian Baez", 815)
altmaier = Player("Daniel Altmaier", 813)
halys = Player("Quentin Halys", 811)
varillas = Player("Juan Pablo Varillas", 808)
o_connell = Player("Christopher O'Connell", 806)
fils = Player("Arthur Fils", 800)
thompson = Player("Jordan Thompson", 798)
zhang = Player("Zhizhen Zhang", 796)
purcell = Player("Max Purcell", 786)
borges = Player("Nuno Borges", 772)
moutet = Player("Corentin Moutet", 768)
wawrinka = Player("Stan Wawrinka", 764)
arnaldi = Player("Matteo Arnaldi", 762)
muller = Player("Alexandre Muller", 748)
van_assche = Player("Luca Van Assche", 748)
wu = Player("Yibing Wu", 743)
ramos_vinolas = Player("Albert Ramos-Vinolas", 742)
draper = Player("Jack Draper", 741)
molcan = Player("Alex Molcan", 731)
rinderknech = Player("Arthur Rinderknech", 721)
vukic = Player("Aleksandar Vukic", 716)
huesler = Player("Marc-Andrea Huesler", 704)
kubler = Player("Jason Kubler", 697)
lestienne = Player("Constant Lestienne", 691)
koepfer = Player("Dominik Koepfer", 691)
kokkinakis = Player("Thanasi Kokkinakis", 667)
kotov = Player("Pavel Kotov", 667)
cachin = Player("Pedro Cachin", 662)
popyrin = Player("Alexei Popyrin", 655)
ivashka = Player("Ilya Ivashka", 652)
marozsan = Player("Fabian Marozsan", 646)
thiem = Player("Dominic Thiem", 631)
cecchinato = Player("Marco Cecchinato", 628)
shevchenko = Player("Alexander Shevchenko", 622)
diaz_acosta = Player("Facundo Diaz Acosta", 616)
schwartzman = Player("Diego Schwartzman", 615)
albot = Player("Radu Albot", 615)
jm_cerundolo = Player("Juan Martin Cerundolo", 615)
kwon = Player("Soonwoo Kwon", 614)
cilic = Player("Marin Cilic", 610)
brooksby = Player("Jenson Brooksby", 610)
watanuki = Player("Yosuke Watanuki", 608)
cressy = Player("Maxime Cressy", 605)
stricker = Player("Dominic Stricker", 605)
bonzi = Player("Benjamin Bonzi", 603)
machac = Player("Tomas Machac", 601)
piros = Player("Zsombor Piros", 596)
munar = Player("Jaume Munar", 595)
goffin = Player("David Goffin", 583)
daniel = Player("Taro Daniel", 580)
coria = Player("Federico Coria", 566)
gojo = Player("Borna Gojo", 560)
mmoh = Player("Michael Mmoh", 558)
hijikata = Player("Rinky Hijikata", 556)
zeppieri = Player("Giulio Zeppieri", 544)
rodionov = Player("Jurij Rodionov", 535)
garin = Player("Cristian Garin", 534)
gaston = Player("Hugo Gaston", 533)
seyboth_wild = Player("Thiago Seyboth Wild", 530)
monteiro = Player("Thiago Monteiro", 529)
kovacevic = Player("Aleksandar Kovacevic", 526)
tabilo = Player("Alejandro Tabilo", 522)
barrios_vera = Player("Tomas Barrios Vera", 519)
isner = Player("John Isner", 515)
martinez = Player("Pedro Martinez", 512)
fognini = Player("Fabio Fognini", 507)

#Round of 128
test_match1 = Match(alcaraz, fognini)
test_match2 = Match(djokovic, martinez)
test_match3 = Match(medvedev, isner)
test_match4 = Match(ruud, barrios_vera)
test_match5 = Match(tsitsipas, tabilo)
test_match6 = Match(rune, kovacevic)
test_match7 = Match(rublev, monteiro)
test_match8 = Match(sinner, seyboth_wild)
test_match9 = Match(fritz, gaston)
test_match10 = Match(tiafoe, garin)
test_match11 = Match(khachanov, rodionov)
test_match12 = Match(auger_aliassime, zeppieri)
test_match13 = Match(norrie, hijikata)
test_match14 = Match(paul, mmoh)
test_match15 = Match(coric, gojo)
test_match16 = Match(musetti, coria)
test_match17 = Match(hurkacz, daniel)
test_match18 = Match(de_minaur, goffin)
test_match19 = Match(zverev, munar)
test_match20 = Match(f_cerundolo, piros)
test_match21 = Match(dimitrov, machac)
test_match22 = Match(carreno_busta, bonzi)
test_match23 = Match(shapovalov, stricker)
test_match24 = Match(struff, cressy)
test_match25 = Match(bautista_agut, watanuki)
test_match26 = Match(jarry, brooksby)
test_match27 = Match(bublik, cilic)
test_match28 = Match(korda, kwon)
test_match29 = Match(evans, jm_cerundolo)
test_match30 = Match(nishioka, albot)
test_match31 = Match(eubanks, schwartzman)
test_match32 = Match(berrettini, diaz_acosta)
test_match33 = Match(lehecka, shevchenko)
test_match34 = Match(etcheverry, cecchinato)
test_match35 = Match(davidovich_fokina, thiem)
test_match36 = Match(griekspoor, marozsan)
test_match37 = Match(kyrgios, ivashka)
test_match38 = Match(mannarino, popyrin)
test_match39 = Match(shelton, cachin)
test_match40 = Match(humbert, kotov)
test_match41 = Match(murray, kokkinakis)
test_match42 = Match(sonego, koepfer)
test_match43 = Match(safiullin, lestienne)
test_match44 = Match(kecmanovic, kubler)
test_match45 = Match(van_de_zandschulp, huesler)
test_match46 = Match(hanfmann, vukic)
test_match47 = Match(wolf, rinderknech)
test_match48 = Match(ruusuvuori, molcan)
test_match49 = Match(gasquet, draper)
test_match50 = Match(barrere, ramos_vinolas)
test_match51 = Match(ymer, wu)
test_match52 = Match(karatsev, van_assche)
test_match53 = Match(zapata_miralles, muller)
test_match54 = Match(fucsovics, arnaldi)
test_match55 = Match(djere, wawrinka)
test_match56 = Match(elahi_galan, moutet)
test_match57 = Match(nakashima, borges)
test_match58 = Match(ofner, purcell)
test_match59 = Match(mcdonald, zhang)
test_match60 = Match(carballes_baena, thompson)
test_match61 = Match(lajovic, fils)
test_match62 = Match(giron, o_connell)
test_match63 = Match(baez, varillas)
test_match64 = Match(altmaier, halys)

print(test_match1.play_match())
print(test_match2.play_match())
print(test_match3.play_match())
print(test_match4.play_match())
print(test_match5.play_match())
print(test_match6.play_match())
print(test_match7.play_match())
print(test_match8.play_match())
print(test_match9.play_match())
print(test_match10.play_match())
print(test_match11.play_match())
print(test_match12.play_match())
print(test_match13.play_match())
print(test_match14.play_match())
print(test_match15.play_match())
print(test_match16.play_match())
print(test_match17.play_match())
print(test_match18.play_match())
print(test_match19.play_match())
print(test_match20.play_match())
print(test_match21.play_match())
print(test_match22.play_match())
print(test_match23.play_match())
print(test_match24.play_match())
print(test_match25.play_match())
print(test_match26.play_match())
print(test_match27.play_match())
print(test_match28.play_match())
print(test_match29.play_match())
print(test_match30.play_match())
print(test_match31.play_match())
print(test_match32.play_match())
print(test_match33.play_match())
print(test_match34.play_match())
print(test_match35.play_match())
print(test_match36.play_match())
print(test_match37.play_match())
print(test_match38.play_match())
print(test_match39.play_match())
print(test_match40.play_match())
print(test_match41.play_match())
print(test_match42.play_match())
print(test_match43.play_match())
print(test_match44.play_match())
print(test_match45.play_match())
print(test_match46.play_match())
print(test_match47.play_match())
print(test_match48.play_match())
print(test_match49.play_match())
print(test_match50.play_match())
print(test_match51.play_match())
print(test_match52.play_match())
print(test_match53.play_match())
print(test_match54.play_match())
print(test_match55.play_match())
print(test_match56.play_match())
print(test_match57.play_match())
print(test_match58.play_match())
print(test_match59.play_match())
print(test_match60.play_match())
print(test_match61.play_match())
print(test_match62.play_match())
print(test_match63.play_match())
print(test_match64.play_match())


'''round of 64'''
test_match65 = Match(test_match1.winner, test_match64.winner)
test_match65.play_match()
test_match66 = Match(test_match2.winner, test_match63.winner)
test_match66.play_match()
test_match67 = Match(test_match3.winner, test_match62.winner)
test_match67.play_match()
test_match68 = Match(test_match4.winner, test_match61.winner)
test_match68.play_match()
test_match69 = Match(test_match5.winner, test_match60.winner)
test_match69.play_match()
test_match70 = Match(test_match6.winner, test_match59.winner)
test_match70.play_match()
test_match71 = Match(test_match7.winner, test_match58.winner)
test_match71.play_match()
test_match72 = Match(test_match8.winner, test_match57.winner)
test_match72.play_match()
test_match73 = Match(test_match9.winner, test_match56.winner)
test_match73.play_match()
test_match74 = Match(test_match10.winner, test_match55.winner)
test_match74.play_match()
test_match75 = Match(test_match11.winner, test_match54.winner)
test_match75.play_match()
test_match76 = Match(test_match12.winner, test_match53.winner)
test_match76.play_match()
test_match77 = Match(test_match13.winner, test_match52.winner)
test_match77.play_match()
test_match78 = Match(test_match14.winner, test_match51.winner)
test_match78.play_match()
test_match79 = Match(test_match15.winner, test_match50.winner)
test_match79.play_match()
test_match80 = Match(test_match16.winner, test_match49.winner)
test_match80.play_match()
test_match81 = Match(test_match17.winner, test_match48.winner)
test_match81.play_match()
test_match82 = Match(test_match18.winner, test_match47.winner)
test_match82.play_match()
test_match83 = Match(test_match19.winner, test_match46.winner)
test_match83.play_match()
test_match84 = Match(test_match20.winner, test_match45.winner)
test_match84.play_match()
test_match85 = Match(test_match21.winner, test_match44.winner)
test_match85.play_match()
test_match86 = Match(test_match22.winner, test_match43.winner)
test_match86.play_match()
test_match87 = Match(test_match23.winner, test_match42.winner)
test_match87.play_match()
test_match88 = Match(test_match24.winner, test_match41.winner)
test_match88.play_match()
test_match89 = Match(test_match25.winner, test_match40.winner)
test_match89.play_match()
test_match90 = Match(test_match26.winner, test_match39.winner)
test_match90.play_match()
test_match91 = Match(test_match27.winner, test_match38.winner)
test_match91.play_match()
test_match92 = Match(test_match28.winner, test_match37.winner)
test_match92.play_match()
test_match93 = Match(test_match29.winner, test_match35.winner)
test_match93.play_match()
test_match94 = Match(test_match30.winner, test_match35.winner)
test_match94.play_match()
test_match95 = Match(test_match31.winner, test_match34.winner)
test_match95.play_match()
test_match96 = Match(test_match32.winner, test_match33.winner)
test_match96.play_match()


'''round of 32'''
test_match97 = Match(test_match65.winner, test_match96.winner)
test_match97.play_match()
test_match98 = Match(test_match66.winner, test_match95.winner)
test_match98.play_match()
test_match99 = Match(test_match67.winner, test_match94.winner)
test_match99.play_match()
test_match100 = Match(test_match68.winner, test_match93.winner)
test_match100.play_match()
test_match101 = Match(test_match69.winner, test_match92.winner)
test_match101.play_match()
test_match102 = Match(test_match70.winner, test_match91.winner)
test_match102.play_match()
test_match103 = Match(test_match71.winner, test_match90.winner)
test_match103.play_match()
test_match104 = Match(test_match72.winner, test_match89.winner)
test_match104.play_match()
test_match105 = Match(test_match73.winner, test_match88.winner)
test_match105.play_match()
test_match106 = Match(test_match74.winner, test_match87.winner)
test_match106.play_match()
test_match107 = Match(test_match75.winner, test_match86.winner)
test_match107.play_match()
test_match108 = Match(test_match76.winner, test_match85.winner)
test_match108.play_match()
test_match109 = Match(test_match77.winner, test_match84.winner)
test_match109.play_match()
test_match110 = Match(test_match78.winner, test_match83.winner)
test_match110.play_match()
test_match111 = Match(test_match79.winner, test_match82.winner)
test_match111.play_match()
test_match112 = Match(test_match80.winner, test_match81.winner)
test_match112.play_match()


'''Round of 16'''
test_match113 = Match(test_match97.winner, test_match112.winner)
test_match113.play_match()
test_match114 = Match(test_match98.winner, test_match111.winner)
test_match114.play_match()
test_match115 = Match(test_match99.winner, test_match110.winner)
test_match115.play_match()
test_match116 = Match(test_match100.winner, test_match109.winner)
test_match116.play_match()
test_match117 = Match(test_match101.winner, test_match108.winner)
test_match117.play_match()
test_match118 = Match(test_match102.winner, test_match107.winner)
test_match118.play_match()
test_match119 = Match(test_match103.winner, test_match106.winner)
test_match119.play_match()
test_match120 = Match(test_match104.winner, test_match105.winner)
test_match120.play_match()


'''Quarter Finals'''
test_match121 = Match(test_match113.winner, test_match120.winner)
test_match121.play_match()
test_match122 = Match(test_match114.winner, test_match119.winner)
test_match122.play_match()
test_match123 = Match(test_match115.winner, test_match118.winner)
test_match123.play_match()
test_match124 = Match(test_match116.winner, test_match117.winner)
test_match124.play_match()


'''Semi Finals'''
test_match125 = Match(test_match121.winner, test_match124.winner)
test_match125.play_match()
test_match126 = Match(test_match122.winner, test_match123.winner)
test_match126.play_match()


'''Final'''
test_match127 = Match(test_match125.winner, test_match126.winner)
test_match127.play_match()

'''Champion'''
print(f"The tournament champion is: {test_match127.winner}")
